export const dummy_users = [
    {
        id:'u1',
        name:'user1',
        avatar:'user-1.jpg'
    },
    {
        id:'u2',
        name:'user2',
        avatar:'user-2.jpg'
    },
    {
        id:'u3',
        name:'user3',
        avatar:'user-3.jpg'
    },
    {
        id:'u4',
        name:'user4',
        avatar:'user-4.jpg'
    },
    {
        id:'u5',
        name:'user5',
        avatar:'user-5.jpg'
    },
    {
        id:'u6',
        name:'user6',
        avatar:'user-5.jpg'
    },
]